CC=gcc
CFLAGS=-g -Wall
all: ahead_128px sharply_left_128px sharply_right_128px slightly_left_128px \
slightly_right_128px turn_left_128px turn_right_128px

.PHONY:
clean:
	$(RM) *~ *.o ahead_128px sharply_left_128px sharply_right_128px \
slightly_left_128px slightly_right_128px turn_left_128px turn_right_128px
