CFLAGS=-g -Wall

all: rgb565_to_argb8888 argb8888_to_bmp bmp_to_argb8888 argb8888_to_rgb565 \
argb8888_to_argb565 printBmpHdr

.PHONY:
clean:
	$(RM) *.o *~  rgb565_to_argb8888 argb8888_to_bmp bmp_to_argb8888 \
argb8888_to_rgb565 argb8888_to_argb565 printBmpHdr
