CC=gcc
CFLAGS=-g -Wall
all: alarm_16px hedgehog info_1_8px info_1_16px battery_icon_64px \
bluetooth_64px brightness_32px brightness_64px call_ok_128px cancel_32px \
check_32px down_32px email_32px email_64px exit_32px facebook_32px \
facebook_64px foot_16px info_2_16px info_2_8px info_3_16px info_3_8px \
info_fail_16px info_fail_8px info_n_16px info_n_8px info_ok_16px info_ok_8px \
info_update_16px info_update_8px instagram_32px instagram_64px \
k9mail_32px k9mail_64px left_32px lock_16px message_32px message_48px \
message_64px move_32px move_64px next_32px next_64px osmand_32px osmand_64px \
pause_32px pause_64px play_32px play_64px prev_32px prev_64px refresh_32px \
right_32px setup_32px setup_64px sound_64px sound_32px sound_mute_32px \
telegram_32px telegram_64px time_32px time_64px tinder_32px tinder_64px \
trash_32px unlock_16px up_32px update_64px utilities_48px utilities_64px \
whatsapp_32px whatsapp_64px wifi_64px youtube_32px youtube_64px \
mondaine_clock_64px calendar_64px calculator_64px status_64px

.PHONY:
clean:
	$(RM) *~ *.o
